Bakery/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bakery.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    [Required(ErrorMessage = "Field cannot be empty!")]
    public string TreatName { get; set; }
    public List<FlavorTreat> JoinEntities { get; }
    public ApplicationUser User { get; set; }
  }
}

Bakery/Controllers/TreatController.cs
using Bakery.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Bakery.Controllers
{
  public class TreatsController : Controller
  {
    private readonly BakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager,BakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
      if(!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
                          .Include(treat => treat.JoinEntities)
                          .ThenInclude(join => join.Flavor)
                          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
      #nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Bakery/Views/Treats/AddFlavor.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Treat

<h2>Add Flavor to this Treat</h2>

<h4>Add a Flavor to @Html.DisplayFor(model => model.TreatName).</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")
  <br/>
  <input type="submit" value="Save" class="btn- btn danger"/>

  <p>@Html.ActionLink("Home", "Index", "Home")</p>
  <p>@Html.ActionLink("Treat List", "Index")</p>
  <p>@Html.ActionLink("Flavors", "Index", "Flavors")</p>
}

Bakery/Views/Treats/Create.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Treat

<h2>Add a treat for @User.Identity.Name</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.TreatName)
  @Html.TextBoxFor(model => model.TreatName)

  <input type="submit" value="Add treat" class="btn btn-danger" id="add_treat_btn"/>
}

<p>@Html.ActionLink("Treat list", "Index")</p>

Bakery/Views/Treats/Delete.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Treat

<h2>Delete this treat?</h2>

@Html.DisplayNameFor(model => model.TreatName) : @Html.DisplayFor(model => model.TreatName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Treat List", "Index")</p>

Bakery/Views/Treats/Details.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@using Bakery.Models
@model Bakery.Models.Treat

<h2>Treat details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.TreatName) : @Html.DisplayFor(model => model.TreatName)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>@Html.DisplayFor(model => model.TreatName) is not associated with any flavors.</p>
}
else
{
  <h4>@Html.DisplayFor(model => model.TreatName) uses the follwing flavors.</h4>
  <ul>
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <li>@join.Flavor.FlavorName</li>
    @using (Html.BeginForm("DeleteJoin", "Treats"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<hr />

<p>@Html.ActionLink("Treat List", "Index")</p>
<p>@Html.ActionLink("Add treat", "Create")</p>
<p>@Html.ActionLink("Edit treat", "Edit", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Add Flavor to this treat", "AddFlavor", new { id = Model.TreatId})</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Bakery/Views/Treats/Edit.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Treat

<h2>Edit Treat</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.TreatName)
  @Html.EditorFor(model => model.TreatName)

  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Treat list", "Index")</p>

Bakery/Views/Treats/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@using Bakery.Models;

<div class="text-center">
  <h1 class="display-4">Add Treats Here<h1>

  @if(Model.Count == 0)
  {
    <h3>Get started by adding a Flavor</h3>
  }
  else
  {
    <ul>
    @foreach (Treat treat in Model)
    {
    <li>@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
    }
    </ul>
  }
</div>

  <hr />
  <p>@Html.ActionLink("Treat List", "Index") | @Html.ActionLink("Add a treat", "Create")</p>