Bakery/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bakery.Models
{
  public class Flavor
  {
    public int FlavorId { get; set; }
    [Required(ErrorMessage = "Field cannot be empty!")]
    public string FlavorName { get; set; }
    public List<FlavorTreat> JoinEntities { get; }
    public ApplicationUser User { get; set; }
  }
}

Bakery/Controllers/FlavorController.cs
using Bakery.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Bakery.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly BakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager,BakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      if(!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
                            .Include(flavor => flavor.JoinEntities)
                            .ThenInclude(join => join.Treat)
                            .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      if (joinEntity == null && treatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Bakery/Views/Flavors/AddTreat.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Flavor

<h2>Add Treat to this Flavor</h2>

<h4>Add a Treat tag to @Html.DisplayFor(model => model.FlavorName).</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select Treat")
  @Html.DropDownList("TreatId")
  <br/>
  <input type="submit" value="Save" class="btn- btn danger"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Flavor List", "Index")</p>
<p>@Html.ActionLink("Treats", "Index", "Treats")</p>

Bakery/Views/Flavors/Create.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Flavor

<h2>Add a Recipe for @User.Identity.Name</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.FlavorName)
  @Html.TextBoxFor(model => model.FlavorName)

  <input type="submit" value="Add Flavor" class="btn btn-danger" id="add_flavor_btn"/>
}

<p>@Html.ActionLink("Flavor List", "Index")</p>

Bakery/Views/Flavors/Delete.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Flavor

<h2>Delete this flavor?</h2>

@Html.DisplayNameFor(model => model.FlavorName) : @Html.DisplayFor(model => model.FlavorName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Flavor List", "Index")</p>

Bakery/Views/Flavors/Details.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@using Bakery.Models
@model Bakery.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.FlavorName) : @Html.DisplayFor(model => model.FlavorName)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>@Html.DisplayFor(model => model.FlavorName) is not associated with any Treats</p>
}
else
{
  <h4>@Html.DisplayFor(model => model.FlavorName) is used in the following treats.</h4>
  <ol>
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <li>@join.Treat.TreatName</li>
    @using (Html.BeginForm("DeleteJoin", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ol>
}

<hr />

<p>@Html.ActionLink("Flavor List", "Index")</p>
<p>@Html.ActionLink("Add flavor", "Create")</p>
<p>@Html.ActionLink("Edit flavor", "Edit", new { id = Model.FlavorId})</p>
<p>@Html.ActionLink("Add Treat to this Flavor", "AddTreat", new { id = Model.FlavorId})</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

Bakery/Views/Flavors/Edit.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@model Bakery.Models.Flavor

<h2>Edit Flavor</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.FlavorName)
  @Html.EditorFor(model => model.FlavorName)
  
  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Flavor List", "Index")</p>

Bakery/Views/Flavors/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

@using Bakery.Models;

<div class="text-center">
  <h1 class="display-4">Add Flavors Here<h2>

  @if(Model.Count == 0)
  {
    <p>Get started by adding a Flavor</p>
  }
  else
  {
    <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.FlavorName}", "Details", new { id = flavor.FlavorId })</li>
    }
    </ul>
  }
</div>

<hr />
<p>@Html.ActionLink("Flavor List", "Index", "Flavors") | @Html.ActionLink("Add a flavor", "Create")</p>